Spa 184 zaimplementowanie endpointu put api posts post
Project-SpeakApp/SpeakApp pull request #10
Opened 2023-12-04 18:58 UTC by MaciekK2001

2023-12-04 20:32 UTC, sebastianp265 requested changes

2023-12-04 20:32 UTC, sebastianp265 commented on backend/post-service/src/main/java/com/speakapp/postservice/controllers/PostController.java
> +            throws ResponseStatusException {
niepotrzebne troche throws ResponseStatusException, bardzo ogólne runtimexception, które nie jest potrzebne, ani nie mówi nic o metodzie - u Michała ma to sens, bo on tam na razie napisał swój CustomException, który mówi co jest obsługiwane w endpoincie

2023-12-04 20:32 UTC, sebastianp265 commented on backend/post-service/src/main/java/com/speakapp/postservice/services/PostService.java
> +        postUpdated.setContent(postCreateDTO.getContent());
Słaba skalowalność w przyszłości, gdy będziemy dodawać jakieś dodatkowe rzeczy do postów, wtedy trzeba będzie zmodyfikować wszystkie użycia w serwisie. Po to używamy mapstructa, tutaj masz sekcje jak zrobić to co chciałeś:
https://mapstruct.org/documentation/stable/reference/html/#mapping-nested-bean-properties-to-current-target

2023-12-04 20:32 UTC, sebastianp265 commented on backend/post-service/src/main/java/com/speakapp/postservice/services/PostService.java
> +        // TODO: delete after complex tests - can be assumed empty (post has been just created)
Komentarz totalnie zbędny tutaj - do usunięcia, napisałem go w swojej metodzie, żebyście mieli gotowca, poza tym komentarz mówi sam za siebie, tutaj nie ma takiej sytuacji jak opisanej w komentarzu

2023-12-04 20:32 UTC, sebastianp265 commented on backend/post-service/src/main/java/com/speakapp/postservice/services/PostService.java
> +        // TODO: delete after complex tests - can be assumed empty (post has been just created)
To samo co UP

2023-12-04 20:32 UTC, sebastianp265 commented on backend/post-service/src/main/java/com/speakapp/postservice/services/PostService.java
> +                null
Tutaj musisz sprawdzić czy user, który edytuje posta, ma przypisaną jakąś reakcję. Ja tego nie napisałem, bo w momencie tworzenia posta nie ma możliwości, żeby była jakakolwiek reakcja (w przypadku komentarzy i ogólnych reakcji dałem swoje implementacje po to, żebyście mieli wzór jak komunikować się z zewnętrznymi serwisami - tutaj musisz zaimplementować to sam)

2023-12-07 10:30 UTC, MaciekK2001 commented
@sebastianp265 rzucisz okiem na poprawki?

2023-12-07 19:51 UTC, sebastianp265 commented
Rozwiązałem konflikty z main branchem, teraz napiszę ci co tam trzeba

2023-12-07 20:37 UTC, sebastianp265 requested changes
Ogólnie trochę czasu minęło od twojego pr i trzeba było zpullować zmiany z maina i rozwiązać konflikty. Zostało w zasadzie poprawienie jednego dosyć istotnego błędu, który warto, żebyś sam zobaczył o co chodzi i poprawił. Dodałem ci opisy, żebyś nie miał wątpliwości, jak coś to pisz komentarz na gh, a w razie jakbym nie odczytał to możesz przypomnieć się na priv.

2023-12-07 20:37 UTC, sebastianp265 commented on backend/post-service/src/main/java/com/speakapp/postservice/repositories/PostReactionRepository.java
> +    PostReaction findByPostAndUserId(Post post, UUID userId);
Arek dodał spoko query pod spodem, do tego co chcesz zrobić, zerknij sobie na jego kod. Na przyszłość jak chcesz dostać jeden obiekt z bazy danych to pamiętaj o opakowaniu w Optional<>, wymusza to na korzystającym z tej metody obsługę sytuacji gdy obiektu nie ma w tabeli - w następnym komie zobaczysz o czym mówiłem.

2023-12-07 20:37 UTC, sebastianp265 commented on backend/post-service/src/main/java/com/speakapp/postservice/repositories/PostRepository.java
> +    Post getPostByPostId(UUID postId);
Tu to samo z brakiem Optional<>

2023-12-07 20:37 UTC, sebastianp265 commented on backend/post-service/src/main/java/com/speakapp/postservice/services/PostService.java
> +        Post postUpdated = postRepository.getPostByPostId(postId);
Gdy nie znajdziesz obiektu w bazie o takim postId to zwróci ci nulla. Konsekwencje tego bedą na dole.

2023-12-07 20:37 UTC, sebastianp265 commented on backend/post-service/src/main/java/com/speakapp/postservice/services/PostService.java
> +        //TODO: Handling Exception when userId != postId
Tu nwm ocb zbytnio

2023-12-07 20:37 UTC, sebastianp265 commented on backend/post-service/src/main/java/com/speakapp/postservice/services/PostService.java
> +        postMapper.updatePostFromPostCreateDTO(postCreateDTO, postUpdated);
Tutaj właśnie będzie problem przez tego nulla, tzn. jeżeli nie znajdziemy obiektu w bazie z podanym postId, to w tym miejscu próbujesz zmapować wartości na obiekt null -> NullPointerException

2023-12-07 20:37 UTC, sebastianp265 commented on backend/post-service/src/main/java/com/speakapp/postservice/services/PostService.java
> +        postRepository.save(postUpdated);
przy metodzie save jest zwracany aktualny obiekt, który stworzy sobie JPA, warto przypisać sobie ten obiekt do zmiennej i później ewentualnie na nim robić kolejne operacje i go ostatecznie zwrócić
powinieneś zrobić coś w stylu:
```
Post updatedPost = postRepository.save(postToUpdate);
```
A wcześniej nazwać post pobierany z bazy jako np. "postToUpdate" - zanim go zapiszesz (wywołasz save) to jest to tak naprawdę "post do aktualizacji"

2023-12-07 20:37 UTC, sebastianp265 commented on backend/post-service/src/main/java/com/speakapp/postservice/services/PostService.java
> +        PostReaction currentUserReaction = postReactionRepository.findByPostAndUserId(postUpdated, userId);
Tu spoko, ale ostatecznie skorzystaj z arka query, jest to trochę lepsze rozwiązanie jak tak sobie z nim rozmawiałem a propos jego pull requesta

2023-12-08 14:25 UTC, MaciekK2001 commented on backend/post-service/src/main/java/com/speakapp/postservice/services/PostService.java
> +        //TODO: Handling Exception when userId != postId
to już zmęczenie materiału było, miało być że user wysyłający żadanie jest autorem posta

2023-12-09 13:04 UTC, sebastianp265 commented
```
if (postRepository.getPostByPostId(postId).isEmpty())
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Post of given postId has not been found");
Post postToUpdate = postRepository.getPostByPostId(postId).get();
```
Dwa razy pobierasz post z repo niepotrzebnie, zamiast tego masz to wszystko w jednej operacji:
```
Post postToUpdate = postRepository.findById(postId).orElseThrow(() ->
            new ResponseStatusException(HttpStatus.NOT_FOUND, "Post with id = " + postId + " was not found"));
```

Dodatkowo rzuciło mi się w oko, że stworzyłeś metodę w PostRepository, ale ona bazowo jest.

Dobra robota!
Daje approva ale zmerguj sobie sam, żebyś mógł zerknąć co jeszcze zmieniłem

2023-12-09 13:05 UTC, sebastianp265 approved these changes

2023-12-09 13:10 UTC, sebastianp265 commented
A sory rzuciła mi się w oko jedna rzecz, nie potrzebujesz ściągać pełnych danych o userze z user service, w encji Post masz już info o autorze, zaraz to poprawie. Zerknij zanim zmergujesz

2023-12-09 15:25 UTC, merged