Spa 166 zaimplementowanie widoku
Project-SpeakApp/SpeakApp pull request #18
Opened 2023-12-11 19:58 UTC by MaciejKuzmicki

Dodałem AddPostComponent i serwis wysyłający zapytania do api. Po wciśnięciu "Post" pojawia się nowa instancja w bazie danych. Jeżeli content jest pusty to nie wykona się zapytanie do bazy danych.

2023-12-11 21:18 UTC, Krezlau requested changes

2023-12-11 21:18 UTC, Krezlau commented on frontend/src/app/app-routing.module.ts
> +  { path: 'posts/create', component: AddPostComponent},
Na razie może być ale jak zrobisz wyświetlanie postów to zawarłbym to w pathie "home", gdzie miałbyś `HomePageComponent` i w nim na górze `AddPostComponent` a niżej liste postów.

2023-12-11 21:18 UTC, Krezlau commented on frontend/src/app/modules/posts/components/add-post/add-post.component.spec.ts
do wywalenia

2023-12-11 21:18 UTC, Krezlau commented on frontend/src/app/modules/posts/components/add-post/add-post.component.ts
> +    if (this.model.content.trim().length > 0) {
Ogólnie do walidacji użyłbym klasy `FormControl` i w parametrach dajesz `Validators.Required` albo `Validators.MinLength(1)` itp.

2023-12-11 21:18 UTC, Krezlau commented on frontend/src/app/modules/posts/components/add-post/add-post.component.ts
> +      this.addPostSubscription = this.PostService.addPost(this.model, this.userId).subscribe({
Nie znam angulara na tyle dobrze, ale nie bezpieczniej jest użyć `add()` zamiast `=`? Nie wiem czy nie ma wycieku jak dodasz kilka postów np.

2023-12-11 21:18 UTC, Krezlau commented on frontend/src/app/modules/posts/components/add-post/add-post.component.ts
> +        error: (error) => {
Tą logikę bym przeniósł do serwisu za pomocą funkcji `pipe()`

2023-12-11 21:18 UTC, Krezlau commented on frontend/src/app/modules/posts/sevices/post.service.spec.ts
do wywalenia

2023-12-11 21:18 UTC, Krezlau commented on frontend/src/app/app.module.ts
> +    FormsModule,
`FormsModule` i te importy potrzebne tutaj?

2023-12-11 21:18 UTC, Krezlau commented on frontend/src/app/modules/posts/sevices/post.service.ts
Tak jak pisałem przeniósłbym tutaj logikę obsługi błędów za pomocą pipe i tap. Dodatkowo fajnie by było jakbyś obsłużył status ładowania za pomocą sygnału. Jak coś to w moim pull requescie jest przykład.

2023-12-11 21:18 UTC, Krezlau commented on frontend/src/app/modules/posts/components/add-post/add-post.component.html
> +        <button class="btn btn-primary" style="float:right; border-radius: 25px">Post</button>
może zamiast "btn" "app-btn"?

2023-12-11 21:28 UTC, MaciejKuzmicki commented on frontend/src/app/app-routing.module.ts
> +  { path: 'posts/create', component: AddPostComponent},
zapomnialem usunac, to w celach testowych miało być

2023-12-11 21:35 UTC, MaciejKuzmicki commented on frontend/src/app/modules/posts/components/add-post/add-post.component.ts
> +      this.addPostSubscription = this.PostService.addPost(this.model, this.userId).subscribe({
w kursie, z którego sie uczyłem angulara, była taka forma pokazana, więc bym zostawił w sumie

2023-12-11 21:43 UTC, Krezlau commented on frontend/src/app/modules/posts/components/add-post/add-post.component.ts
> +      this.addPostSubscription = this.PostService.addPost(this.model, this.userId).subscribe({
ok, w sumie będę musiał popatrzeć jak jest z tymi wyciekami

2023-12-12 09:35 UTC, MaciejKuzmicki commented
Poprawiłem błędy, które wymieniłeś

2023-12-12 12:24 UTC, Krezlau requested changes

2023-12-12 12:24 UTC, Krezlau commented on frontend/src/app/modules/posts/sevices/post.service.ts
> +    new Promise(resolve => setTimeout(resolve, 5000));
to chyba z testowania ci zostało 🤔 (polecam ustawić w debuggerze chroma throttling na networku generalnie jak testujesz state ładowania)

2023-12-12 12:24 UTC, Krezlau commented on frontend/src/app/app.component.html
> +  <app-add-post ></app-add-post>
chyba też z testowania ci zostało

2023-12-12 12:34 UTC, MaciejKuzmicki commented on frontend/src/app/app.component.html
> +  <app-add-post ></app-add-post>
juz usuwam

2023-12-12 12:37 UTC, Krezlau approved these changes
git

2023-12-12 12:37 UTC, merged