Add post reaction endpoint
Project-SpeakApp/SpeakApp pull request #30
Opened 2023-12-18 01:08 UTC by arkadiuszc2

Utworzenie endpointu umożliwiającego dodawanie reakcji do posta. Po dodaniu reakcji zwrócone zostaje DTO z informacjami o statystykach reakcji dla danego posta.

**UWAGA**
Tego endpointu nie było do tej pory w dokumentacji - trzeba ustalić jak chcemy podejść do dodawania reakcji (jak mają wyglądać endpointy). Narazie zaimpementowałem to w taki prostu sposób żeby coś było, jak ustalimy szczegóły to dodam zmiany.

**Testowanie**
Zrobiłem prosty test uruchamiając cały backend, działało poprawnie - statystyki reakcji dla posta były prawidłowo aktualizowane.

2023-12-19 18:17 UTC, Michal-Szlazak reviewed
Ogólnie wszystko działa - ale wg. JIRY dla reakcji miał być UpSert (Update i Insert).
Twoja implementacja pozwala dodawać dowolną ilość reakcji przez użytkownika do posta co technicznie nie powinno być możliwe.

Ale znowu tworzenie ustalonego UpSertu (który jednocześnie tworzy lub update'uje) też chyba nie jest możliwe bo frontend do stworzenia reakcji musiałby wysyłać nieistniejący reaction_id - bo PUT tworzy nową encję tylko gdy próbuje się update'ować encję z nieistniejącym ID (o ile dobrze rozumiem).

Więc imo dla tabeli post_reaction powinien być ustawiony uniqueConstraint dla kolumn post_id i user_id - żeby uniknąć dalszych błędów (Query w PostReactionRepository oczekuje pojedyńczej wartości i wtedy jak będzie kilka reakcji też sie wywali exception z tego co wiem)

no i chyba najlepiej jest zrobić POST PUT i DELETE i sie nie bawić w upsert. tylko wtedy w POST powinno być sprawdzone czy użytkownik nie wstawił już wcześniej reakcji.

2023-12-19 20:47 UTC, Michal-Szlazak requested changes
(To przestarzały pr) Do ogarnięcia na przyszły sprint.

2024-01-03 23:46 UTC, arkadiuszc2 commented
Utworzenie endpointu do aktualizacji reakcji użytkownika na post. Endpoint utworzony w formie upsert, obsługuje zarówno utworzenie reakcji jak również update reakcji. 

**API docs**
Dodałem dokumentację endpointu w naszych api docs.

**Testowanie**
Utworzyłem gotowe do wysłania requesty (plik z rozszerzeniem .http). Sprawdzałem odpowiedzi na te requesty oraz przez postmana sprawdzałem czy widać zmiany wyświetlając listę najnowszych postów i sprawdzając czy reakcje zmieniają się tak jak powinny po wysłaniu wcześniej wspomnianych requestów.

2024-01-04 22:57 UTC, Michal-Szlazak approved these changes
Wygląda spoczko i działa spoczko - jedynie bym sie zastanowił nad zrobieniem oddzielnego kontrolera i serwisu dla PostReaction dla przejrzystości, ale to zawsze można później w jakiejś refaktoryzacji zrobić więc daje approve'a

2024-01-06 12:27 UTC, merged