Spa 219 sortowanie komentarzy
Project-SpeakApp/SpeakApp pull request #44
Opened 2024-01-10 12:36 UTC by Michal-Szlazak

Dodałem endpointy do sortowania komentarzy.

 - /api/comments/by-created-at
 - /api/comments/by-reactions 

dodatkowym parametrem jest sort - "asc" lub "desc", przy błędnym inpucie wyjdzie "desc"

Metody są do siebie bardzo podobne więc próbowałem zrobić jedną ogólną ale przez to że ilość reakcji to nie pole w komentarzu to się nie da tego zrobić bez Query w repozytorium (przynajmniej nic nie znalazłem). Więc zrobiłem tak żeby było jak najmniej kodu.

Sprawdzałem przez swaggera i plik http

2024-01-11 15:51 UTC, Krezlau requested changes

2024-01-11 15:51 UTC, Krezlau commented on backend/post-service/src/main/java/com/speakapp/postservice/repositories/CommentRepository.java
> +    Page<Comment> findAllByPostOrderByReactionsDesc(@Param("post") Post post, Pageable pageable);
nie wystarczy po prostu dodać parametru do `PageRequest.of`?
Takie coś jest na baeldung:
``` 
Pageable sortedByName = 
  PageRequest.of(0, 3, Sort.by("name"));

Pageable sortedByPriceDesc = 
  PageRequest.of(0, 3, Sort.by("price").descending());

Pageable sortedByPriceDescNameAsc = 
  PageRequest.of(0, 5, Sort.by("price").descending().and(Sort.by("name")));
```
https://www.baeldung.com/spring-data-jpa-pagination-sorting

2024-01-11 15:51 UTC, Krezlau commented on backend/post-service/src/main/java/com/speakapp/postservice/controllers/CommentController.java
> +    @GetMapping("/by-reactions")
wiem, że tego nie ma na jirze, ale lepiej byłoby rozwiązać to wszystko za pomocą opcjonalnych parametrów to zwykłej funkcji getowania komentarzy.

Może coś w stylu `sortByReactions: "asc" | "desc"` i `sortByCreatedAt: "asc" | "desc"`?

2024-01-11 15:53 UTC, Krezlau commented on backend/post-service/src/main/java/com/speakapp/postservice/repositories/CommentRepository.java
> +    Page<Comment> findAllByPostOrderByReactionsDesc(@Param("post") Post post, Pageable pageable);
Jeśli dodanie w komentarzu pola z ilością reakcji by ułatwiło to wszystko, to może dobrze by było to zrobić? Tylko wtedy trzeba zadbać o odpowiednie aktualizowanie go.

2024-01-13 12:39 UTC, Michal-Szlazak commented
Dodałem zmienną numberOfReactions do encji Comment. Dzięki temu można dla Comments wystarczy stworzyć tylko jeden endpoint z parametrem sortBy oraz sortDirection gdzie trzeba podać kolumne po której chce się sortować.

Defaultowo wartości są ustawione na sortBy=createdAt i sortDirection=DESC więc endpoint dla normalnego GET się nie zmienił.

Parametr sortBy nie jest sprawdzany więc można sortować po dowolnej kolumnie. Przy wprowadzeniu nieistniejącej wartości wyrzucony będzie PropertyReferenceException - ale wydaje mi się że lepiej go złapać w ControllerAdvice niż w samej metodzie (dzięki temu przy zmianie encji nie trzeba będzie edytować metody).

2024-01-15 14:20 UTC, Krezlau approved these changes
Teraz wygląda spoko, aczkolwiek nie testowałem

2024-02-02 14:28 UTC, merged