Spa 217 zaimplementowanie endpointu put api posts comments comment
Project-SpeakApp/SpeakApp pull request #45
Opened 2024-01-10 20:50 UTC by MaciekK2001

Zaimplementowany endpoint PUT. Dodatkowo stworzyłem osobne foldery dla testów dla poszczególnych serwisów(posts, comments, reactions)

2024-01-11 16:02 UTC, Krezlau requested changes
niech ktoś też z backendu jeszcze odpali i potestuje

2024-01-11 16:03 UTC, Krezlau commented on backend/post-service/src/main/java/com/speakapp/postservice/services/CommentService.java
> +        if(lengthOfContent > 500 || lengthOfContent == 0){
zamiast tego użyłbym dekoratorów w DTO i dał w kontrolerze przy `CommentUpdateDTO` dekorator `@Valid`.

2024-01-11 16:04 UTC, MaciekK2001 commented on backend/post-service/src/main/java/com/speakapp/postservice/services/CommentService.java
> +        if(lengthOfContent > 500 || lengthOfContent == 0){
ok, poprawie

2024-01-11 16:36 UTC, MaciekK2001 commented
Poprawiłem(to samo zrobiłem dla dodawania komentarzy, tam też była walidacja w serwisie), przy okazji poprawiłem błąd, w CommentUpdateDTO niepotrzbny był parametr postId, który nie powinien być.

2024-01-12 11:09 UTC, MaciekK2001 commented
Również dodany tu został przypadkiem task z dodawania, usuwania, aktualizowania reakcji pod komentarzami.

2024-01-12 23:38 UTC, Michal-Szlazak approved these changes
Działa - ale na pewno przydałoby się zrobić reafactoring w tych klasach bo wiele kodu się powtarza + pozwoliłem sobie dodać klamerki do jednolinijkowych if'ów

2024-01-15 14:26 UTC, Krezlau reviewed
@Michal-Szlazak O jaki refactoring ci chodzi? Może lepiej zrobić to od razu?

2024-01-15 14:26 UTC, Krezlau commented on backend/post-service/src/main/java/com/speakapp/postservice/services/ReactionService.java
> +                "Comment with provided commentId" + commentId + "does not exist"));
wiem że się czepiam szczegółów ale tutaj ci się sklei i wyjdzie coś "Comment with provided commentId036fd207-b7a7-48d3-bf43-a45f8faa31cfdoes not exist"

2024-01-15 14:26 UTC, Krezlau commented on backend/post-service/src/main/java/com/speakapp/postservice/services/ReactionService.java
> +        Comment comment = commentRepository.findById(commentId).orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND,
może by się dało tutaj zrobić jakąś generic metodę? Chociaż nie wiem na ile to potrzebne tak naprawdę

2024-01-15 16:48 UTC, Michal-Szlazak commented
> @Michal-Szlazak O jaki refactoring ci chodzi? Może lepiej zrobić to od razu?

No ogólnie technicznie serwisy powinny korzystać ze swoich repozytoriów, a z innymi repozytoriami sie komunikować przez inne serwisy. Dlatego właśnie ten commentRepository.findById() powinien być raczej w CommentService i wywołany w ReactionSerwis (przez CommentSerwis).

Ale takie rzeczy mamy w całym projekcie dlatego sobie pomyślałem że już lepiej to zrobić na raz i od razu powywalać odwołania do repozytoriów. I też nie jestem pewien o ile to polepszy przejrzystość.

i tworzenie CommentGetDTO się powtarza 3 razy (tj jakoś 6 linijek) więc dla czytelności można by było jakąś metodę stworzyć do tego

2024-01-15 17:11 UTC, Krezlau commented
> > @Michal-Szlazak O jaki refactoring ci chodzi? Może lepiej zrobić to od razu?
> 
> No ogólnie technicznie serwisy powinny korzystać ze swoich repozytoriów, a z innymi repozytoriami sie komunikować przez inne serwisy. Dlatego właśnie ten commentRepository.findById() powinien być raczej w CommentService i wywołany w ReactionSerwis (przez CommentSerwis).

Nie wiem jakie są standardy w javie ale chyba powinno być ok umieszczanie repo w serwisie.

2024-02-05 18:31 UTC, Krezlau approved these changes

2024-02-05 18:31 UTC, Krezlau commented
tylko proszę rozwiązać konflikty

2024-02-05 22:32 UTC, merged