Spa 237 obsluga wyjatkow w user service
Project-SpeakApp/SpeakApp pull request #49
Opened 2024-02-06 15:15 UTC by arkadiuszc2

Dokładnie ten sam mechanizm obsługi wyjątków co w post service.

2024-02-26 20:10 UTC, Michal-Szlazak requested changes
Nie udało mi się tego uruchomić, brakuje jakichś plików.

PostService korzysta z spring-exception-handler a user-service też ma z niego importy ale brakuje plików do pobrania spring-exception-handler + zostały klasy z przed spring-exception-handler.

ale nawet po zmianie importu i tak mi sie nie udało uruchomić - ale to może moja wina

2024-02-26 20:10 UTC, Michal-Szlazak commented on backend/user-service/src/main/java/com/speakapp/userservice/exception_handler/GlobalExceptionHandler.java
> +import com.speakapp.springexceptionhandler.ServiceLayerException;
tutaj nie znajduje mi importu + istnieje jeszcze klasa utowrzona w exeptions

2024-02-26 23:34 UTC, arkadiuszc2 commented
Ogólnie śmieszna sytuacja bo błąd nie wynikał z kodu w user-service tylko z tego że na tym branchu był stary kod w post-service, który używał jeszcze poprzedniego rozwiązania obsługi wyjątków (próbował pobrać zewnętrzną bibliotekę którą stworzyłem). Zpullowałem zmiany z brancha z obsługą wyjątków w post-service, już normalnie można zbudować i uruchomić projekt.

Poprawiłem jeszcze ten import o którym pisałeś i pousuwałem trochę niepotrzebnych importów z kilku klas. 

Przetestowałem na endpoincie do pobierania informacji o użytkowniku podając nieistniejącego użytkownika -  odpowiedź informująca o błędzie była odpowiednia więc wygląda na to że wszystko działa jak powinno.

2024-02-27 20:41 UTC, Michal-Szlazak approved these changes
Działa wszystko na moje oko.

2024-02-29 00:55 UTC, merged