Spa 218 frontend sortowanie komentarzy
Project-SpeakApp/SpeakApp pull request #51
Opened 2024-02-08 10:36 UTC by MaciejKuzmicki

Zrobiłem sortowanie komentarzy, poprawiłem też obsługę dodawania i usuwania komentarza

2024-02-10 11:40 UTC, Krezlau requested changes
ogólnie super, jedna tylko uwaga z mojej strony

2024-02-10 11:40 UTC, Krezlau commented on frontend/src/app/modules/posts/components/comment-list/comment-list.component.ts
> +    if(this.totalComments == 0) return;
tutaj lepiej chyba będzie dać ===

2024-02-10 11:40 UTC, Krezlau commented on frontend/src/app/modules/posts/components/sort-comments/sort-comments.component.ts
> +  sortOrder: string = "DESC";
Co sądzisz o daniu tutaj typu, który będzie nam to jeszcze zabezpieczał?
np enum stworzyć albo dać typ w stylu: `'DESC' | 'ASC'`

2024-02-19 22:08 UTC, MaciejKuzmicki commented
Uwzględniłem uwagi, powstał enum SortOrder

2024-02-19 22:10 UTC, Krezlau approved these changes

2024-02-19 22:12 UTC, merged