Spa 230 discovery service
Project-SpeakApp/SpeakApp pull request #57
Opened 2024-03-07 22:21 UTC by KarolSekscinski

Połowiczny sukces, ze tak powiem. 

Udało mi się ustawić discovery server - eurekę, post-service user-service i gateway-service wyświetlają się na serwerze ale nie działa poprawnie automatyczny routing, wiec na razie zostawiam statycznie wpisane numery portów (dodanie komponentu load balancera powinno załatwić sprawę, ale to na oddzielny pr). 

Ponadto dodałem config server na którym można dodawać wspólne konfiguracje dla mikro serwisów.

Zmieniłem strukturę docker compose'a (aby discovery server mógł odnajdywać serwisy to musiały one być w jednej sieci).

Jak sobie klikałem FE to wszystko działało, ale polecałbym to sprawdzić przez osobę która wiedziała co wcześniej działało.

2024-03-15 15:43 UTC, Michal-Szlazak requested changes
Ogólnie wszystko wygląda git (na tyle na ile to rozumiem).

Jedyne co to w plikach konfiguracyjnych post-service i user-service są te same konfiguracje inaczej ustawiane więc można by było wybrać jedno rozwiązanie. (np w post-service jest application-cloud.yml a w user-service nie ma, albo w user-service jest pusty bootstrap.yml - a wsm wszędzie są te same ustawienia tylko w innych plikach)

W configservice jest pusty eureka-server.yml, jeżeli nie jest potrzebny to też można by wywalić.

2024-03-15 21:10 UTC, KarolSekscinski commented
Próbowałem drugi raz używać automatycznego load balancera z Eureki do automatycznego routingu, ale bezskutecznie. Gateway wtedy chciałby dostać się np. do post-service przez http://post-service:80 i wyskakuje błąd 503 (SERVICE_UNAVAILABLE) bo post-service cały czas działa na 8082. Jakby ktoś chciał się pobawić w rozwiazywanie tego problemu to zapraszam, ja już niestety nie mam na to siły, zostawiam uri z portami.

2024-03-16 12:59 UTC, Michal-Szlazak commented
Sorry że sie czepiam, zapomniałem napisać w poprzednim review. Wydaje mi sie że fajnie gdyby podział na osobne sieci w compose.yml został - chyba że usunięcie ich zostało gdzieś ustalone i tego nie zauważyłem.
Wtedy serwisy razem z gatewayem by się połączyło we wspólną sieć żeby discovery-service je wykrywał ale nie będzie jednego głównego bridge'a do którego wszystko jest podłączone.

2024-03-16 15:25 UTC, KarolSekscinski commented
No może tak zostać z podziałem, chociaż mam wrażenie, że to tylko niepotrzebnie komplikuje compose'a.

2024-03-17 10:57 UTC, Krezlau commented
Z perspektywy frontu wygląda jakby wszystko działało. @Michal-Szlazak jesteś pewien co do tych networków. Trochę nie widzę żeby nam pomagały z czymkolwiek, a tylko komplikują. Aczkolwiek to nie jest duża różnica w sumie.

2024-03-17 12:32 UTC, Michal-Szlazak commented
Albo trzeba wybrać izolację kontenerów albo prostotę - pan Szef backendowy ps. Seba wybrał izolację tworząc compose'a, więc tego się trzymam, jeżeli chcemy coś takiego zmienić to bym się jego pytał

jakby to powiedział świetny wykładowca - whatever

2024-03-17 12:35 UTC, Krezlau commented
ok no to chyba można to mergować nie?

2024-03-17 12:54 UTC, Michal-Szlazak approved these changes

2024-03-17 14:54 UTC, merged