Spa 242 inicjalizacja i konfiguracja web socket w i bazy danych message db i konwersacje prywatne i chatPreview
Project-SpeakApp/SpeakApp pull request #69
Opened 2024-04-08 18:15 UTC by MaciekK2001

2024-04-15 11:04 UTC, KarolSekscinski commented
Maciek zaktualizuj swój branch do main, bo jesteś 141 commitow za mainem

2024-04-16 11:57 UTC, Michal-Szlazak requested changes
Pododawałem komentarze co moim zdaniem powinno być do zmiany - ale to tylko sugestie bo nwm czy to co napisaliście nie wynika z jakichś problemów o których nie wiem.

Poza tym brakuje Exception handlingu - myślę że lepiej od razu zrobić niż czekać na później (chodzi mi o controller advice i customowe exceptions).

2024-04-16 11:57 UTC, Michal-Szlazak commented on backend/chat-service/src/main/java/com/chatservice/communication/UserServiceCommunicationClient.java
Tutaj technicznie żeby była zgodność z PostService, przy is4xxClientError powinien być zwracany UserNotFoundException

2024-04-16 11:57 UTC, Michal-Szlazak commented on backend/chat-service/src/main/java/com/chatservice/dtos/MessagePrivateCreateDTO.java
Zmienne UUID raczej powinny mieć dopisek Id na końcu dla lepszej przejrzystości.

2024-04-16 11:57 UTC, Michal-Szlazak commented on backend/chat-service/src/main/java/com/chatservice/dtos/NewPrivateConversationDTO.java
Tutaj też powinno być conversationMemberUserId

2024-04-16 11:57 UTC, Michal-Szlazak commented on backend/chat-service/src/main/java/com/chatservice/entities/Message.java
Tutaj też fromUserId

2024-04-16 11:57 UTC, Michal-Szlazak commented on backend/chat-service/src/main/java/com/chatservice/entities/MessageSeen.java
tutaj messageId powinno być message

2024-04-16 11:57 UTC, Michal-Szlazak commented on backend/chat-service/src/main/java/com/chatservice/mappers/MessageMapper.java
Jak nie używane to do wywalenia.

2024-04-16 11:57 UTC, Michal-Szlazak commented on backend/chat-service/src/main/java/com/chatservice/repositories/ConversationRepository.java
To jest dość mocno nieefektywne - przeszukiwanie wszystkich istniejących konwersacji po jej użytkownikach.
Myślałem że konwersacja prywatna nie będzie miała generowanego identyfikatora tylko ustawiany ręcznie np.: userId1_userId2 - wtedy można je łatwo wyszukać. Tylko inne rozwiązanie trzeba będzie znaleźć dla konersacji grupowych.

2024-04-16 11:57 UTC, Michal-Szlazak commented on backend/chat-service/src/main/java/com/chatservice/services/ChatService.java
> +        Conversation createdConversation = conversationRepository.save(conversationMapper.toEntity(false));
Tutaj mapper do ustawienia jednej hardcodowanej zmiennej bym odpuścił bo ciężko się to czyta.

2024-04-16 11:57 UTC, Michal-Szlazak commented on backend/chat-service/src/main/java/com/chatservice/repositories/MessageRepository.java
Tutaj też mi się wydaje że dużo danych jest przeglądane, pewnie lepiej by było przechowywać w konwersacji ostatnią wysłaną wiadomość.

2024-04-16 11:57 UTC, Michal-Szlazak commented on backend/chat-service/src/main/java/com/chatservice/entities/GroupMember.java
Tutaj też żeby było podobnie do innych joinedDatetime - joinedAt, leftDatetime - leftAt.

2024-04-29 22:06 UTC, sebastianp265 commented
Wygląda ok, parę metod w repositories wisi nieużywane, poza tym spoko. Jak do tej pory to testowałeś? Wypadałoby spojrzeć na tabele przy usuwaniu kaskadowym, jeżeli tego nie zerkałeś. Powoli można zamykać pr, trzeba pamiętać o modyfikacji w gatewayu do obsługi serwisu i przed mergem przetestować z postmanem np.

2024-04-30 13:14 UTC, MaciekK2001 commented
Testy są w resources dla tworzenia konwersacji prywatnych i przeglądania chat-preview. Dla testowania websocketów można wejść na localhost:8084 i tam jako nazwa użytkownika podać randomowe UUID (ponieważ będziemy wysyłali wiadomości na UUID). Te testy websocketów to trochę spaghetti jeśli chodzi o kod, ale no miało sprawdzić czy działa a działają one mniej więcej tak:
Każdy nowy użytkownik subskrybuje ten sam kanał (domyślnie będzie subskrybował swój własny) i wysyła wiadomości na ten kanał, czyli wszyscy sobie piszą tak jakby w jednym czacie, no i rzeczywiście to działa.

2024-05-01 18:54 UTC, Michal-Szlazak approved these changes
Sprawdzać czy wszystko działa nie sprawdziłem - ale wygląda wporzo. W razie co bugi będziemy poprawiać na bierząco.

2024-05-01 18:54 UTC, Michal-Szlazak commented on backend/chat-service/src/main/java/com/chatservice/dtos/MessageGetDTO.java
> +    UserGetDTO fromUserId;
Tutaj powinno być bez Id.

2024-05-01 18:55 UTC, merged