Spa 247 load balancer
Project-SpeakApp/SpeakApp pull request #72
Opened 2024-04-20 03:04 UTC by KarolSekscinski

Wiec tak, obecna konfiguracja gateway'a przerzuca mnie do dobrego portu tylko po nazwie (czyli DNS działa), lecz dostaje błąd connection refused. 
Proszę o weryfikacje czy u innych również występuje ten problem, bo na moim dockerze dzieją się różne dziwne rzeczy ostatnio.
Jeśli będzie problem to dalej do tego usiądę, chyba ze ktoś inny chce się pobawić.

Miałem tez dużo problemów z siecią, np. mikro serwisy przestawały działać bo nie mogły się połączyć ze swoja baza, tak samo z keycloakiem ale po uproszczeniu sieciowym compose'a problem zniknął.
Nadal jestem za tym, żeby upraszczać a nie komplikować.
Dodatkowo docker desktop zużywa wtedy mniej zasobów i szybciej się ładuje wiec same plusy.

2024-05-14 14:17 UTC, Krezlau requested changes
Jest to samo co mówisz, z api otrzymuję taki response:
```json
{
    "timestamp": "2024-05-14T14:16:36.420+00:00",
    "path": "/api/posts",
    "status": 500,
    "error": "Internal Server Error",
    "requestId": "69a8d762"
}
```
i w api gatewayu jest connection refused
![image](https://github.com/Project-SpeakApp/SpeakApp/assets/92681896/aa908a90-9a9e-432b-904f-5f2b0351a03b)
![image](https://github.com/Project-SpeakApp/SpeakApp/assets/92681896/aa908a90-9a9e-432b-904f-5f2b0351a03b)

2024-05-26 22:22 UTC, KarolSekscinski commented
Wszystko śmiga po mojej głębokiej analizie i testowaniu, proszę o weryfikacje poprawności.
Zmiany:
- od teraz każdy mikroserwis działa na porcie 80 dla http - gateway ma loadbalancowane ścieżki także wszystko śmiga - komentarze, posty, reakcje, zdjęcia się dodają (chat-service tez sorry @MaciekK2001 mam nadzieje ze nic ci nie popsułem, ustawie tez później eureke pod chat)
- w compose nie ma jasno zdefiniowanego portu dla kontenera - cala komunikacja opiera się tylko na DNS wewnątrz compose - te wprost zdefiniowane porty chyba były powodem dlaczego tak długo nie byłem w stanie tego rozkminic

2024-05-27 18:23 UTC, Krezlau reviewed
wygląda jakby działało, ale poczekamy na ssl najpierw

2024-05-27 21:41 UTC, KarolSekscinski commented
smiga po zmergowaniu, polecam kliknac tu VVVV

2024-05-28 14:15 UTC, KarolSekscinski commented
Ustawilem eureka i config na SPA-82 pod chat, tam dzialalo

2024-05-29 07:13 UTC, Krezlau approved these changes

2024-05-29 07:13 UTC, merged