SPA-74 (& SPA-75) - Dodawanie avatarów / zdjęć w tle
Project-SpeakApp/SpeakApp pull request #74
Opened 2024-04-22 14:26 UTC by Krezlau

*Najpierw należy zmergować SPA-76)*

Dodałem możliwość zmiany avatara/zdjęcia w tle (to ze zdjęciem w tle będzie trzeba się zastanowić nad przycinaniem itp. ale to kiedy indziej i guess bo wymagałoby to też backendu chyba)

2024-04-24 20:29 UTC, MaciejKuzmicki commented on frontend/src/app/modules/posts/components/add-post/add-post.component.ts
> +  imageSubstription = new Subscription();
literówka xd

2024-04-24 20:34 UTC, MaciejKuzmicki commented on frontend/src/app/modules/profiles/components/profile/profile.component.ts
> +  imageSubstription = new Subscription();
kolejna literowka, znacyz jak nie chcesz to nie poprawiaj XDD

2024-04-24 20:35 UTC, MaciejKuzmicki commented on frontend/src/app/shared/components/user-avatar/user-avatar.component.ts
> +  imageSubstription = new Subscription();
+1

2024-04-24 20:36 UTC, MaciejKuzmicki commented on frontend/src/app/shared/services/auth.service.ts
>  import {Router} from "@angular/router";
nieuzywany import

2024-04-24 20:36 UTC, MaciejKuzmicki commented on frontend/src/app/shared/services/auth.service.ts
>  import {Router} from "@angular/router";
nieuzywany import Router

2024-04-24 20:39 UTC, MaciejKuzmicki requested changes
Generalnie działa to super, zastanowiłbym się tylko nad obsługą dodania pliku o innym rozszerzeniu niż obsługiwane. Gdy dodaje plik .html zamiast zdjęcia to dostaje informacje "Something went wrong" 
![image](https://github.com/Project-SpeakApp/SpeakApp/assets/95870273/77e25df1-9b81-4b64-ac8d-0d13bec21a13)
i pozostaje potem symbol ładowania.
Dodatkowo dobrze, aby była też możliwość edycji zdjęcia przy poście, a tak poza tym to super.

2024-05-06 12:24 UTC, MaciejKuzmicki requested changes
Ogółem to avatary działają dobrze, mam kilka sugestii co do postów:
1. Nie wiem czy nie dodać możliwości edycji zdjęcia przypisanego do postu (na razie można tylko usunąć)
2. Usunięcie zdjęcia nie powoduje wyświetlenia komunikatu "Edited ${date}" a poniekąd jest to edycja postu
3. Z jakiegoś powodu nie mogę utworzyć dwóch postów bezpośrednio jeden po drugim z tym samym zdjęciem

2024-05-06 12:24 UTC, MaciejKuzmicki commented on frontend/src/app/modules/posts/components/add-post/add-post.component.ts
> +import {pipe, Subscription, tap} from 'rxjs';
pipe nieużywany

2024-05-12 11:50 UTC, Krezlau commented
> Ogółem to avatary działają dobrze, mam kilka sugestii co do postów:
> 
> 1. Nie wiem czy nie dodać możliwości edycji zdjęcia przypisanego do postu (na razie można tylko usunąć)
> 2. Usunięcie zdjęcia nie powoduje wyświetlenia komunikatu "Edited ${date}" a poniekąd jest to edycja postu
> 3. Z jakiegoś powodu nie mogę utworzyć dwóch postów bezpośrednio jeden po drugim z tym samym zdjęciem

ad. 1. Na razie zostawmy bez, nie mam pomysłu za bardzo jak miało by to wyglądać w ui

2024-05-14 19:11 UTC, MaciejKuzmicki approved these changes
Wszystko git

2024-05-14 19:12 UTC, merged