Spa 191 implementacja endpointu /api/users/{userId} GET
Project-SpeakApp/SpeakApp pull request #9
Opened 2023-12-04 16:30 UTC by Michal-Szlazak

Utworzyłem controller, service, i repository dla AppUser - bez ErrorHandlingu. Endpoint GET jest niezmieniony ("/api/users/{userId}") ale wartość podana w url jest ignorowana i brana z header'a.

Dodałem zależność dla swaggera do sprawdzania działania endpointów.

2023-12-04 19:00 UTC, MaciekK2001 approved these changes

2023-12-04 20:12 UTC, sebastianp265 requested changes
Dodałem komentarze do tego co jest na ten moment nie tak z kodem, poza tym jednym błędem to wszystko git, dobra robota

2023-12-04 20:12 UTC, sebastianp265 commented on backend/user-service/src/main/java/com/speakapp/userservice/controllers/UserController.java
> +import com.speakapp.userservice.dtos.AppUserCreateDTO;
wyrzuca błąd - przed mergem do mastera trzeba usunąć importa

2023-12-04 20:12 UTC, sebastianp265 commented on backend/user-service/src/main/java/com/speakapp/userservice/dtos/AppUserDTO.java
> +public class AppUserDTO {
Ustawiłeś wszystkie pola AppUserDTO na private i nie można defacto przez to zbudować obiektu, jak sobie spojrzysz do wygenerowanej przez mapstruct klasy to przez to nie ustawiają ci się pola

Polecam dodać:
@Value
@Builder
@Jacksonized

Wtedy można darować sobie nawet pisanie private - @Value ustawi bazowo pola na private :)

Zaktualizuj dodatkowo nazwy pól na zdefiniowane w api docs w jirze - był tam duży syf i niespójności, teraz powinno być ok

2023-12-04 20:12 UTC, sebastianp265 commented on backend/user-service/pom.xml
> -                        <exclude>
Nie wiem czemu usunąłeś exclude lombok - jest do generowane by default przez spring initializer

https://stackoverflow.com/questions/45202639/should-lombok-have-a-provided-scope-in-spring-boot-dependencies
https://stackoverflow.com/questions/74718709/why-i-have-to-add-exclusion-in-spring-boot-maven-plugin-while-using-lombok

2023-12-05 14:49 UTC, sebastianp265 approved these changes
Super robota, dodałem małą zmianę, żeby zwracało kod 404 jak nie ma usera

2023-12-05 14:49 UTC, merged

2023-12-05 14:51 UTC, sebastianp265 commented
A i przerzuciłem taska na jirze na "Gotowe"