Spa 265 rabbit mq
Project-SpeakApp/SpeakApp pull request #98
Opened 2024-05-27 21:28 UTC by KarolSekscinski

Dzień dobry, dodałem kolejkę, user i post service produkują podczas usuwania lub zmiany zdjęć wiadomości do niej a mój piękny kontener w py pobiera wiadomości z kolejki i usuwa z Azurite. Dziękuje pięknie za uwagę.

2024-05-27 21:44 UTC, KarolSekscinski commented
Up to date z main

2024-05-27 21:44 UTC, KarolSekscinski commented
Polecam kliknac tu VVVV

2024-05-27 21:47 UTC, KarolSekscinski commented
Off topic - można sobie elegancko podglądać działanie kolejki tu: http://localhost:15672

2024-05-28 19:46 UTC, Michal-Szlazak requested changes
Dodałem spowrotem usunięte rzeczy z compose'a - bez nich apka by nie trybiła.

Po przekazaniu wiadomości z rabbitMQ do consumer'a (nwm o czym mówię) wyskakuje taki błąd:

ERROR - Unexpected error: The API version 2024-05-04 is not supported by Azurite. Please upgrade Azurite to latest version and retry. If you are using Azurite in Visual Studio, please check you have installed latest Visual Studio patch. Azurite command line parameter "--skipApiVersionCheck" or Visual Studio Code configuration "Skip Api Version Check" can skip this error.

i zdjęcie dalej jest w blobie.

Jednak mój błąd miałem złą wersję XD (docker...)

2024-05-28 22:26 UTC, Michal-Szlazak approved these changes
Po zrobieniu zadymy stwierdzam że jednak działa.

2024-05-28 22:27 UTC, merged